--- 
- 
  data: "CREATE TABLE `friends_map` (\n  `user_id` int(10) unsigned NOT NULL,\n  `friend_id` int(10) unsigned NOT NULL,\n  PRIMARY KEY (`user_id`,`friend_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8"
  schema: friends_map
- 
  data: "CREATE TABLE `locations` (\n  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n  `prefecture` varchar(255) NOT NULL,\n  `city` varchar(255) NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8"
  schema: locations
- 
  data: "CREATE TABLE `users` (\n  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n  `nickname` varchar(255) NOT NULL,\n  `age` tinyint(3) unsigned NOT NULL,\n  `some_flg` tinyint(3) unsigned DEFAULT NULL,\n  `location_id` int(10) unsigned NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8"
  schema: users
